version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: access-agenda-app
    volumes:
      - vendor:/var/www/html/vendor
      - node_modules:/var/www/html/node_modules
      - type: bind
        source: .
        target: /var/www/html
        consistency: cached
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    image: nginx:stable-alpine
    container_name: access-agenda-nginx
    ports:
      - "8090:80"
    volumes:
      - type: bind
        source: .
        target: /var/www/html
        consistency: cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: access-agenda-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  node:
    image: node:18-alpine
    container_name: access-agenda-node
    working_dir: /var/www/html
    volumes:
      - vendor:/var/www/html/vendor
      - node_modules:/var/www/html/node_modules
      - type: bind
        source: .
        target: /var/www/html
        consistency: cached
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5174:5173"
    networks:
      - app-network


volumes:
  dbdata:
  vendor:
  node_modules:

networks:
  app-network:
    driver: bridge
